sudo: enabled
language: java
jdk: oraclejdk13

services:
- xvfb #Display Virtual
- mysql #Base de datos



before_install:
  - sudo apt-get update #Actualiza paquetes
  - sudo apt-get install dbus-x11 #instalacion de dbus -x11
  - export DISPLAY=:99.0 #Crear un display virtual
  - sleep 3 #Darle chance al xvfb de iniciar
  - export CHROME_BIN=/usr/bin/google-chrome #Config variable
  - sudo apt-get install -y libappindicator1 fonts-liberation #Dependencias para Chromium
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb #Descargamos Chrome
  - sudo dpkg -i google-chrome*.deb #Instalamos Chrome
  - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip #Descargamos ChromeDriver
  - unzip chromedriver_linux64.zip #Descomprimimos ChromeDriver
  - sudo cp chromedriver /usr/bin #Acomodamos ChromeDriver en el bin


  - mysql -u root --password="" < SQLTest/dummy.sql #Proceso para MySQL, usando mi dummy script


script: 
- mvn clean #Aseguramos que surefire pueda correr sin problemas
- mvn test #Iniciamos proceso de pruebas de Maven
- mvn surefire:test -Dtest=funcionales #Por medio de surefire, aseguramos que se pruebe el test de funcionales

- DfailIfNoTests=false #Util para continuar haciendo pruebas aunque no se encuentre un Test


notifications:
 email: false #A este punto ya tenia 20 correos basura sobre travis
 